// Generated by dts-bundle-generator v9.5.1

export type Role = "SUPER_ADMIN" | "ADMIN" | "SUPPORT" | "COURIER";
export type Mode = "RETAIL" | "BATCH";
export type IssueKind = "TICKET" | "DISPUTE";
export type MarketplaceDistribution = Record<string, number>;
export type DashboardGroupBy = "day" | "week" | "month";
export type HandLimitRule = {
	minDisputePercent?: number;
	maxDisputePercent: number;
	maxHandPercent: number;
	payoutLimit?: number;
	blockPayouts?: boolean;
};
export type BonusRule = {
	name: string;
	enabled?: boolean;
	bonusPercent: number;
	minAddresses?: number;
	maxDisputePercent?: number;
	depositRequired?: number;
	logic?: string;
};
export type BonusSettings = {
	period?: string;
	addressThreshold?: number;
	maxPercent?: number;
	depositMskSpb?: number;
	depositRegions?: number;
	rules?: BonusRule[];
};
export type DisputeRuleConfig = {
	none?: boolean;
	cost?: boolean;
	work?: boolean;
	retail?: boolean;
	retailPercentEnabled?: boolean;
	retailPercent?: number;
	damagePercentEnabled?: boolean;
	damagePercent?: number;
	fullDamage?: boolean;
	manual?: boolean;
};
export declare function previewIssueAllocation(input: {
	actorLogin: string;
	courierId: string;
	batchId: string;
	cityId: string;
	productId: string;
	weight: number;
	stashType: string;
	marketplace: string;
}): Promise<{
	found: boolean;
	dataEntryId: string;
	free: number;
	marketplaceQuantity: number;
	used: number;
} | {
	found: boolean;
	dataEntryId: null;
	free: number;
	marketplaceQuantity: number;
	used: number;
}>;
export declare function health(): Promise<{
	status: string;
	timestamp: string;
	db: string;
	env: "development" | "production";
}>;
export declare function getAppState(): Promise<{
	employees: {
		id: string;
		createdAt: Date;
		status: string;
		updatedAt: Date;
		login: string;
		password: string;
		role: string;
		handBalance: number;
		depositBalance: number;
		bankBalance: number;
	}[];
	cities: {
		id: string;
		createdAt: Date;
		name: string;
		status: string;
		updatedAt: Date;
	}[];
	products: {
		id: string;
		createdAt: Date;
		name: string;
		status: string;
		updatedAt: Date;
	}[];
	citySettings: {
		id: string;
		createdAt: Date;
		status: string;
		updatedAt: Date;
		cityId: string;
		productId: string;
		mode: string;
	}[];
	priceRates: {
		id: string;
		createdAt: Date;
		cityId: string;
		productId: string;
		mode: string;
		weight: number;
		price: number;
	}[];
	stashTypes: {
		id: string;
		createdAt: Date;
		name: string;
		updatedAt: Date;
		cityId: string;
		productId: string;
		mode: string;
		surcharge: number;
	}[];
	marketplaces: {
		id: string;
		createdAt: Date;
		name: string;
		status: string;
		updatedAt: Date;
	}[];
	batches: {
		id: string;
		createdAt: Date;
		name: string;
		status: string;
		updatedAt: Date;
		cityId: string;
		productId: string;
		weight: number;
		totalBatchCost: number;
		warehouseWorkCost: number;
		remainingGram: number;
		costPerGram: number;
		fasEnabled: boolean;
		fasCost: number;
		fasPackages: number;
		courierId: string | null;
		issuedAt: Date | null;
		closedAt: Date | null;
		closeReason: string | null;
		retailCloseSum: number | null;
	}[];
	dataEntries: {
		id: string;
		createdAt: Date;
		updatedAt: Date;
		cityId: string;
		productId: string;
		mode: string;
		courierId: string;
		batchId: string;
		weightPerAddr: number;
		stashTypeName: string;
		quantity: number;
		mpDistribution: string;
		grossWeight: number;
		earnings: number;
		processed: boolean;
	}[];
	issues: {
		id: string;
		createdAt: Date;
		status: string;
		updatedAt: Date;
		stashType: string | null;
		weight: number;
		marketplace: string | null;
		calcType: string | null;
		courierId: string;
		closedAt: Date | null;
		batchId: string | null;
		couponPercent: number | null;
		kind: string;
		dataEntryId: string | null;
		orderNumber: string | null;
		retailPrice: number;
		problemIds: string;
		otherText: string | null;
		decisionId: string | null;
		calculationData: string | null;
		writeOff: number;
	}[];
	issueAllocations: {
		id: string;
		createdAt: Date;
		cityId: string;
		productId: string;
		stashType: string;
		weight: number;
		marketplace: string | null;
		courierId: string;
		batchId: string;
		dataEntryId: string;
		issueRecordId: string;
	}[];
	monthlySettlements: {
		id: string;
		createdAt: Date;
		courierId: string;
		periodFrom: Date;
		periodTo: Date;
		soldQuantity: number;
		uploadedQuantity: number;
		disputeCount: number;
		openDisputeCount: number;
		ticketCount: number;
		disputePercent: number;
		openDisputePercent: number;
		courierStatusName: string;
		courierStatusRuleId: string | null;
		totalDisputeWriteOff: number;
		bonusAmount: number;
		requestedBankPayout: number;
		finalBankPayout: number;
		createdBy: string;
	}[];
	settlementWriteOffs: {
		id: string;
		createdAt: Date;
		courierId: string;
		couponPercent: number | null;
		retailPrice: number;
		decisionId: string | null;
		calculationData: string;
		issueRecordId: string;
		settlementId: string;
		statusRuleName: string;
		writeOffAmount: number;
	}[];
	penalties: {
		id: string;
		createdAt: Date;
		courierId: string;
		issueId: string | null;
		amount: number;
		applyCourierStatus: boolean;
		stashDeduction: boolean;
		reason: string;
		bankWrittenOff: number;
		depositWrittenOff: number;
	}[];
	financeProcessing: {
		id: string;
		createdAt: Date;
		status: string;
		remainingGram: number;
		courierId: string;
		batchId: string;
		earnings: number;
		dataEntryId: string;
		maxHand: number;
		handAmount: number;
		depositAmount: number;
		bankAmount: number;
		processedAt: Date | null;
	}[];
	financeLedger: {
		type: string;
		id: string;
		createdAt: Date;
		settlementId: string | null;
		amount: number;
		employeeId: string;
		note: string | null;
	}[];
	problemTypes: {
		id: string;
		createdAt: Date;
		name: string;
		updatedAt: Date;
	}[];
	decisions: {
		id: string;
		createdAt: Date;
		name: string;
		updatedAt: Date;
		calcType: string;
		percent: number;
		manualAmount: number;
	}[];
	statusRules: {
		blockPayouts: boolean;
		id: string;
		createdAt: Date;
		name: string;
		updatedAt: Date;
		minPercent: number;
		maxPercent: number | null;
		description: string;
		paysWhat: string;
		returnRules: string;
		returnLogic: string;
		returnPercent: number;
		couponRules: string;
		couponLogic: string;
		couponPercent: number;
		manualMode: boolean;
		workBlocked: boolean;
		payoutLimit: number | null;
		depositRequired: number;
		extraCriteria: string | null;
	}[];
	settings: {
		updatedAt: Date;
		key: string;
		value: string;
	}[];
	logs: {
		id: string;
		userId: string | null;
		userLogin: string;
		action: string;
		entity: string;
		details: string;
		oldValue: string | null;
		newValue: string | null;
		createdAt: Date;
	}[];
	courierStats: {
		addresses: number;
		disputes: number;
		disputePercent: number;
		statusName: string;
		status: {
			blockPayouts: boolean;
			id: string;
			createdAt: Date;
			name: string;
			updatedAt: Date;
			minPercent: number;
			maxPercent: number | null;
			description: string;
			paysWhat: string;
			returnRules: string;
			returnLogic: string;
			returnPercent: number;
			couponRules: string;
			couponLogic: string;
			couponPercent: number;
			manualMode: boolean;
			workBlocked: boolean;
			payoutLimit: number | null;
			depositRequired: number;
			extraCriteria: string | null;
		} | null;
		courierId: string;
	}[];
}>;
export declare function getDashboardAnalytics(input: {
	actorLogin: string;
	from?: string;
	to?: string;
	groupBy?: DashboardGroupBy;
	marketplace?: string;
}): Promise<{
	period: {
		from: string | undefined;
		to: string | undefined;
		groupBy: DashboardGroupBy;
		marketplace: string;
	};
	summary: {
		addresses: number;
		grams: number;
		earnings: number;
		entries: number;
		batches: number;
		activeCouriers: number;
		marketplaces: number;
		disputes: number;
		openDisputes: number;
		closedDisputes: number;
		tickets: number;
		openTickets: number;
		writeOff: number;
		disputePercent: number;
	};
	marketplaceRows: {
		name: string;
		status: string;
		addresses: number;
		grams: number;
		earnings: number;
		disputes: number;
		openDisputes: number;
		closedDisputes: number;
		tickets: number;
		writeOff: number;
		disputePercent: number;
	}[];
	timeline: {
		key: string;
		addresses: number;
		grams: number;
		earnings: number;
		disputes: number;
		tickets: number;
		writeOff: number;
	}[];
	courierRows: {
		courierId: string;
		login: string;
		status: string;
		addresses: number;
		disputes: number;
		disputePercent: number;
		statusName: string;
		earnings: number;
		writeOff: number;
		bankBalance: number;
		depositBalance: number;
	}[];
	finance: {
		ledgerByType: Record<string, number>;
		income: number;
		expense: number;
		penalties: number;
		balances: {
			hand: number;
			deposit: number;
			bank: number;
		};
	};
	disputes: {
		problemRows: {
			name: string;
			count: number;
		}[];
		decisionRows: {
			name: string;
			count: number;
			writeOff: number;
		}[];
		manualDisputes: number;
		autoDisputes: number;
		writeOff: number;
	};
	dataQuality: {
		zeroMpEntries: number;
		unprocessedFinanceRows: number;
	};
}>;
export declare function loginEmployee(input: {
	login: string;
	password: string;
}): Promise<{
	id: string;
	createdAt: Date;
	status: string;
	updatedAt: Date;
	login: string;
	password: string;
	role: string;
	handBalance: number;
	depositBalance: number;
	bankBalance: number;
}>;
export declare function createCity(input: {
	actorLogin: string;
	name: string;
}): Promise<{
	id: string;
	createdAt: Date;
	name: string;
	status: string;
	updatedAt: Date;
}>;
export declare function createEmployee(input: {
	actorLogin: string;
	login: string;
	password: string;
	role: Role;
}): Promise<{
	id: string;
	createdAt: Date;
	status: string;
	updatedAt: Date;
	login: string;
	password: string;
	role: string;
	handBalance: number;
	depositBalance: number;
	bankBalance: number;
}>;
export declare function updateEmployee(input: {
	actorLogin: string;
	id: string;
	password?: string;
	role?: Role;
	status?: string;
}): Promise<{
	id: string;
	createdAt: Date;
	status: string;
	updatedAt: Date;
	login: string;
	password: string;
	role: string;
	handBalance: number;
	depositBalance: number;
	bankBalance: number;
}>;
export declare function createBatch(input: {
	actorLogin: string;
	name: string;
	cityId: string;
	productId: string;
	weight: number;
}): Promise<{
	id: string;
	createdAt: Date;
	name: string;
	status: string;
	updatedAt: Date;
	cityId: string;
	productId: string;
	weight: number;
	totalBatchCost: number;
	warehouseWorkCost: number;
	remainingGram: number;
	costPerGram: number;
	fasEnabled: boolean;
	fasCost: number;
	fasPackages: number;
	courierId: string | null;
	issuedAt: Date | null;
	closedAt: Date | null;
	closeReason: string | null;
	retailCloseSum: number | null;
}>;
export declare function issueBatch(input: {
	actorLogin: string;
	batchId: string;
	courierId: string;
	totalBatchCost: number;
	warehouseWorkCost?: number;
	fasEnabled?: boolean;
	fasCost?: number;
	fasPackages?: number;
}): Promise<{
	id: string;
	createdAt: Date;
	name: string;
	status: string;
	updatedAt: Date;
	cityId: string;
	productId: string;
	weight: number;
	totalBatchCost: number;
	warehouseWorkCost: number;
	remainingGram: number;
	costPerGram: number;
	fasEnabled: boolean;
	fasCost: number;
	fasPackages: number;
	courierId: string | null;
	issuedAt: Date | null;
	closedAt: Date | null;
	closeReason: string | null;
	retailCloseSum: number | null;
}>;
export declare function closeBatch(input: {
	actorLogin: string;
	batchId: string;
	retailCloseSum?: number;
	reason?: string;
}): Promise<{
	id: string;
	createdAt: Date;
	name: string;
	status: string;
	updatedAt: Date;
	cityId: string;
	productId: string;
	weight: number;
	totalBatchCost: number;
	warehouseWorkCost: number;
	remainingGram: number;
	costPerGram: number;
	fasEnabled: boolean;
	fasCost: number;
	fasPackages: number;
	courierId: string | null;
	issuedAt: Date | null;
	closedAt: Date | null;
	closeReason: string | null;
	retailCloseSum: number | null;
}>;
export declare function createDataEntry(input: {
	actorLogin: string;
	courierId: string;
	batchId: string;
	cityId: string;
	mode: Mode;
	weightPerAddr: number;
	stashTypeName: string;
	quantity: number;
	mpDistribution: MarketplaceDistribution;
}): Promise<{
	id: string;
	createdAt: Date;
	updatedAt: Date;
	cityId: string;
	productId: string;
	mode: string;
	courierId: string;
	batchId: string;
	weightPerAddr: number;
	stashTypeName: string;
	quantity: number;
	mpDistribution: string;
	grossWeight: number;
	earnings: number;
	processed: boolean;
}>;
export declare function editDataEntry(input: {
	actorLogin: string;
	id: string;
	courierId: string;
	batchId: string;
	cityId: string;
	mode: Mode;
	weightPerAddr: number;
	stashTypeName: string;
	quantity: number;
	mpDistribution: MarketplaceDistribution;
}): Promise<{
	id: string;
	createdAt: Date;
	updatedAt: Date;
	cityId: string;
	productId: string;
	mode: string;
	courierId: string;
	batchId: string;
	weightPerAddr: number;
	stashTypeName: string;
	quantity: number;
	mpDistribution: string;
	grossWeight: number;
	earnings: number;
	processed: boolean;
}>;
export declare function calculateFinance(input: {
	actorLogin: string;
	processingId: string;
	handAmount: number;
	depositAmount: number;
	bankAmount: number;
	disableLimit?: boolean;
}): Promise<{
	id: string;
	createdAt: Date;
	status: string;
	remainingGram: number;
	courierId: string;
	batchId: string;
	earnings: number;
	dataEntryId: string;
	maxHand: number;
	handAmount: number;
	depositAmount: number;
	bankAmount: number;
	processedAt: Date | null;
}>;
export declare function openIssue(input: {
	actorLogin: string;
	kind: IssueKind;
	orderNumber?: string;
	courierId: string;
	batchId: string;
	cityId: string;
	productId: string;
	weight: number;
	marketplace: string;
	stashType: string;
	retailPrice: number;
	problemIds: string[];
	otherText?: string;
}): Promise<{
	id: string;
	createdAt: Date;
	status: string;
	updatedAt: Date;
	stashType: string | null;
	weight: number;
	marketplace: string | null;
	calcType: string | null;
	courierId: string;
	closedAt: Date | null;
	batchId: string | null;
	couponPercent: number | null;
	kind: string;
	dataEntryId: string | null;
	orderNumber: string | null;
	retailPrice: number;
	problemIds: string;
	otherText: string | null;
	decisionId: string | null;
	calculationData: string | null;
	writeOff: number;
}>;
export declare function closeTicket(input: {
	actorLogin: string;
	issueId: string;
}): Promise<{
	id: string;
	createdAt: Date;
	status: string;
	updatedAt: Date;
	stashType: string | null;
	weight: number;
	marketplace: string | null;
	calcType: string | null;
	courierId: string;
	closedAt: Date | null;
	batchId: string | null;
	couponPercent: number | null;
	kind: string;
	dataEntryId: string | null;
	orderNumber: string | null;
	retailPrice: number;
	problemIds: string;
	otherText: string | null;
	decisionId: string | null;
	calculationData: string | null;
	writeOff: number;
}>;
export declare function closeDispute(input: {
	actorLogin: string;
	issueId: string;
	decisionId: string;
	couponPercent?: number;
	manualAmount?: number;
}): Promise<{
	id: string;
	createdAt: Date;
	status: string;
	updatedAt: Date;
	stashType: string | null;
	weight: number;
	marketplace: string | null;
	calcType: string | null;
	courierId: string;
	closedAt: Date | null;
	batchId: string | null;
	couponPercent: number | null;
	kind: string;
	dataEntryId: string | null;
	orderNumber: string | null;
	retailPrice: number;
	problemIds: string;
	otherText: string | null;
	decisionId: string | null;
	calculationData: string | null;
	writeOff: number;
}>;
export declare function applyPenalty(input: {
	actorLogin: string;
	courierId: string;
	issueId?: string;
	amount: number;
	applyCourierStatus: boolean;
	stashDeduction: boolean;
	reason: string;
}): Promise<{
	id: string;
	createdAt: Date;
	courierId: string;
	issueId: string | null;
	amount: number;
	applyCourierStatus: boolean;
	stashDeduction: boolean;
	reason: string;
	bankWrittenOff: number;
	depositWrittenOff: number;
}>;
export declare function previewBankPayout(input: {
	actorLogin: string;
	employeeId: string;
	amount: number;
	applyBonus: boolean;
	soldQuantity: number;
	periodFrom?: string;
	periodTo?: string;
}): Promise<{
	employee: undefined;
	status: undefined;
	period: {
		start: Date;
		end: Date;
	};
	soldQuantity: number;
	uploadedQuantity: number;
	ticketCount: number;
	disputeCount: number;
	openDisputeCount: number;
	disputePercent: number;
	openDisputePercent: number;
	statusName: string;
	unsettledClosedDisputes: number;
	disputeWriteOffs: {
		issueId: string;
		orderNumber: string | null;
		decisionId: string | null;
		retailPrice: number;
		couponPercent: number | null;
		writeOff: number;
		calculationData: string;
	}[];
	totalDisputeWriteOff: number;
	bankWrittenOff: number;
	depositWrittenOff: number;
	bankAfterWriteOff: number;
	depositAfterWriteOff: number;
	periodEarnings: number;
	bonusPercent: number;
	bonusAmount: number;
	bonusChecks: {
		name: string;
		bonusPercent: number;
		applied: boolean;
		reason: string;
	}[];
	requestedBankPayout: number;
	finalBankPayout: number;
	finalBankBalance: number;
}>;
export declare function payoutBank(input: {
	actorLogin: string;
	employeeId: string;
	amount: number;
	applyBonus: boolean;
	soldQuantity: number;
	periodFrom?: string;
	periodTo?: string;
}): Promise<{
	settlementId: string;
	paid: number;
	bonus: number;
	totalDisputeWriteOff: number;
	remainingBank: number;
}>;
export declare function upsertMarketplace(input: {
	actorLogin: string;
	id?: string;
	name: string;
	status: string;
}): Promise<{
	id: string;
	createdAt: Date;
	name: string;
	status: string;
	updatedAt: Date;
}>;
export declare function deleteMarketplace(input: {
	actorLogin: string;
	id: string;
}): Promise<{
	success: boolean;
	mode: string;
	item: {
		id: string;
		createdAt: Date;
		name: string;
		status: string;
		updatedAt: Date;
	};
}>;
export declare function updateCity(input: {
	actorLogin: string;
	id: string;
	name?: string;
	status?: string;
}): Promise<{
	id: string;
	createdAt: Date;
	name: string;
	status: string;
	updatedAt: Date;
}>;
export declare function deleteCity(input: {
	actorLogin: string;
	id: string;
}): Promise<{
	success: boolean;
	mode: string;
	item: {
		id: string;
		createdAt: Date;
		name: string;
		status: string;
		updatedAt: Date;
	};
}>;
export declare function updateProduct(input: {
	actorLogin: string;
	id: string;
	name: string;
	status?: string;
}): Promise<{
	id: string;
	createdAt: Date;
	name: string;
	status: string;
	updatedAt: Date;
}>;
export declare function deleteProduct(input: {
	actorLogin: string;
	id: string;
}): Promise<{
	success: boolean;
	mode: string;
	item: {
		id: string;
		createdAt: Date;
		name: string;
		status: string;
		updatedAt: Date;
	};
}>;
export declare function updateStashType(input: {
	actorLogin: string;
	id: string;
	name: string;
	surcharge: number;
}): Promise<{
	id: string;
	createdAt: Date;
	name: string;
	updatedAt: Date;
	cityId: string;
	productId: string;
	mode: string;
	surcharge: number;
}>;
export declare function deleteStashType(input: {
	actorLogin: string;
	id: string;
}): Promise<{
	success: boolean;
	mode: string;
	item: {
		id: string;
		createdAt: Date;
		name: string;
		updatedAt: Date;
		cityId: string;
		productId: string;
		mode: string;
		surcharge: number;
	};
}>;
export declare function updateCityProductSetting(input: {
	actorLogin: string;
	cityId: string;
	productId: string;
	mode: Mode;
	status: string;
}): Promise<{
	id: string;
	createdAt: Date;
	status: string;
	updatedAt: Date;
	cityId: string;
	productId: string;
	mode: string;
}>;
export declare function updatePriceRate(input: {
	actorLogin: string;
	cityId: string;
	productId: string;
	mode: Mode;
	weight: number;
	price: number;
}): Promise<{
	id: string;
	createdAt: Date;
	cityId: string;
	productId: string;
	mode: string;
	weight: number;
	price: number;
}>;
export declare function deletePriceRate(input: {
	actorLogin: string;
	id: string;
}): Promise<{
	success: boolean;
	mode: string;
	item: {
		id: string;
		createdAt: Date;
		cityId: string;
		productId: string;
		mode: string;
		weight: number;
		price: number;
	};
}>;
export declare function createCourierStatusRule(input: {
	actorLogin: string;
	name: string;
	minPercent: number;
	maxPercent?: number | null;
	description: string;
	paysWhat: string;
	returnRules?: DisputeRuleConfig;
	returnLogic?: string;
	returnPercent?: number;
	couponRules?: DisputeRuleConfig;
	couponLogic?: string;
	couponPercent?: number;
	manualMode?: boolean;
	workBlocked?: boolean;
	blockPayouts: boolean;
	payoutLimit?: number | null;
	depositRequired: number;
	extraCriteria?: string | null;
}): Promise<{
	blockPayouts: boolean;
	id: string;
	createdAt: Date;
	name: string;
	updatedAt: Date;
	minPercent: number;
	maxPercent: number | null;
	description: string;
	paysWhat: string;
	returnRules: string;
	returnLogic: string;
	returnPercent: number;
	couponRules: string;
	couponLogic: string;
	couponPercent: number;
	manualMode: boolean;
	workBlocked: boolean;
	payoutLimit: number | null;
	depositRequired: number;
	extraCriteria: string | null;
}>;
export declare function updateCourierStatusRule(input: {
	actorLogin: string;
	id: string;
	name: string;
	minPercent: number;
	maxPercent?: number | null;
	description: string;
	paysWhat: string;
	returnRules?: DisputeRuleConfig;
	returnLogic?: string;
	returnPercent?: number;
	couponRules?: DisputeRuleConfig;
	couponLogic?: string;
	couponPercent?: number;
	manualMode?: boolean;
	workBlocked?: boolean;
	blockPayouts: boolean;
	payoutLimit?: number | null;
	depositRequired: number;
	extraCriteria?: string | null;
}): Promise<{
	blockPayouts: boolean;
	id: string;
	createdAt: Date;
	name: string;
	updatedAt: Date;
	minPercent: number;
	maxPercent: number | null;
	description: string;
	paysWhat: string;
	returnRules: string;
	returnLogic: string;
	returnPercent: number;
	couponRules: string;
	couponLogic: string;
	couponPercent: number;
	manualMode: boolean;
	workBlocked: boolean;
	payoutLimit: number | null;
	depositRequired: number;
	extraCriteria: string | null;
}>;
export declare function deleteCourierStatusRule(input: {
	actorLogin: string;
	id: string;
}): Promise<{
	success: boolean;
	mode: string;
	item: {
		blockPayouts: boolean;
		id: string;
		createdAt: Date;
		name: string;
		updatedAt: Date;
		minPercent: number;
		maxPercent: number | null;
		description: string;
		paysWhat: string;
		returnRules: string;
		returnLogic: string;
		returnPercent: number;
		couponRules: string;
		couponLogic: string;
		couponPercent: number;
		manualMode: boolean;
		workBlocked: boolean;
		payoutLimit: number | null;
		depositRequired: number;
		extraCriteria: string | null;
	};
}>;
export declare function restoreDefaultCourierStatusRules(input: {
	actorLogin: string;
}): Promise<{
	success: boolean;
	restored: string[];
}>;
export declare function updateSetting(input: {
	actorLogin: string;
	key: string;
	value: string;
}): Promise<{
	updatedAt: Date;
	key: string;
	value: string;
}>;
export declare function updateHandLimitRules(input: {
	actorLogin: string;
	rules: HandLimitRule[];
}): Promise<{
	updatedAt: Date;
	key: string;
	value: string;
}>;
export declare function updateBonusRules(input: {
	actorLogin: string;
	settings: BonusSettings;
}): Promise<{
	updatedAt: Date;
	key: string;
	value: string;
}>;
export declare function addProblemType(input: {
	actorLogin: string;
	name: string;
}): Promise<{
	id: string;
	createdAt: Date;
	name: string;
	updatedAt: Date;
}>;
export declare function updateProblemType(input: {
	actorLogin: string;
	id: string;
	name: string;
}): Promise<{
	id: string;
	createdAt: Date;
	name: string;
	updatedAt: Date;
}>;
export declare function deleteProblemType(input: {
	actorLogin: string;
	id: string;
}): Promise<{
	success: boolean;
	mode: string;
	item: {
		id: string;
		createdAt: Date;
		name: string;
		updatedAt: Date;
	};
}>;
export declare function addDisputeDecision(input: {
	actorLogin: string;
	name: string;
	calcType: string;
	percent?: number;
	manualAmount?: number;
}): Promise<{
	id: string;
	createdAt: Date;
	name: string;
	updatedAt: Date;
	calcType: string;
	percent: number;
	manualAmount: number;
}>;
export declare function updateDisputeDecision(input: {
	actorLogin: string;
	id: string;
	name: string;
	calcType?: string;
	percent?: number;
	manualAmount?: number;
}): Promise<{
	id: string;
	createdAt: Date;
	name: string;
	updatedAt: Date;
	calcType: string;
	percent: number;
	manualAmount: number;
}>;
export declare function deleteDisputeDecision(input: {
	actorLogin: string;
	id: string;
}): Promise<{
	success: boolean;
	mode: string;
	item: {
		id: string;
		createdAt: Date;
		name: string;
		updatedAt: Date;
		calcType: string;
		percent: number;
		manualAmount: number;
	};
}>;
export declare function clearLogs(input: {
	actorLogin: string;
}): Promise<{
	success: boolean;
}>;

export {};
